dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
script:
  - pytest
jobs:
  include:
    - stage: deploy
      python: "3.7"
      install:
        - pip install .
        - pip install sphinx sphinx-rtd-theme
      script:
        - sphinx-apidoc -f -o docs/_apidoc fmflow
        - sphinx-build docs docs/_build
        - sphinx-build docs docs/_build
      deploy:
        provider: pages
        local-dir: docs/_build
        target-branch: gh-pages
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        keep-history: true
        on:
          branch: master
